-- Comprehensive internship data seeding with 30+ internships across multiple industries

-- Finance & Banking Internships
INSERT INTO internships (
  title, company, description, requirements, skills, location, duration, 
  stipend, start_date, end_date, positions_available, internship_type, 
  status, created_by, salary_min, salary_max, work_schedule, company_size,
  industry, job_category, perks, selection_process, tags,
  created_at, updated_at
) VALUES
(
  'Investment Banking Analyst Intern',
  'Goldman Sachs',
  'Work on financial modeling, valuation analysis, and M&A transactions. You''ll gain exposure to capital markets and work with senior bankers on deals impacting billions.',
  ARRAY['Finance or Economics background', 'Excel expertise', 'Financial modeling experience'],
  ARRAY['Excel', 'Financial Modeling', 'Valuation', 'SQL', 'Python'],
  'New York, NY',
  '10 weeks',
  8000,
  '2024-06-01'::date,
  '2024-08-15'::date,
  8,
  'full-time',
  'active',
  'admin-user',
  7500,
  9000,
  'Monday-Friday, 50+ hours/week',
  'Large (10,000+)',
  'Finance',
  'Investment Banking',
  ARRAY['Competitive stipend', 'Return offer potential', 'Networking dinners', 'Visa sponsorship'],
  'Online test, 3 rounds of interviews',
  ARRAY['banking', 'finance', 'NYC', 'high-pay'],
  NOW(),
  NOW()
),
(
  'Quantitative Analysis Intern',
  'Jane Street',
  'Build and test trading strategies using statistical analysis and machine learning. Work with cutting-edge technologies in algorithmic trading.',
  ARRAY['Strong math background', 'Programming experience', 'Probability and statistics'],
  ARRAY['Python', 'C++', 'Statistics', 'Machine Learning', 'Data Analysis'],
  'New York, NY',
  '12 weeks',
  7500,
  '2024-06-15'::date,
  '2024-09-15'::date,
  12,
  'full-time',
  'active',
  'admin-user',
  7000,
  8500,
  'Monday-Friday, 40 hours/week',
  'Medium (1,000-10,000)',
  'Finance',
  'Quantitative Analysis',
  ARRAY['Free lunch and snacks', 'Gym membership', 'Tech gadgets', 'Mentorship program'],
  'Phone screening, coding challenges, final round',
  ARRAY['quant', 'trading', 'NYC', 'math-heavy'],
  NOW(),
  NOW()
),
(
  'Financial Analyst Intern',
  'JPMorgan Chase',
  'Analyze financial statements, build forecasting models, and support portfolio management. Work across multiple business lines.',
  ARRAY['Business or Finance major', 'Analytical skills', 'Familiarity with financial concepts'],
  ARRAY['Excel', 'Financial Analysis', 'SQL', 'Python', 'Bloomberg Terminal'],
  'Chicago, IL',
  '10 weeks',
  6000,
  '2024-06-01'::date,
  '2024-08-15'::date,
  20,
  'full-time',
  'active',
  'admin-user',
  5500,
  6500,
  'Monday-Friday, 40 hours/week',
  'Large (10,000+)',
  'Finance',
  'Financial Analysis',
  ARRAY['Relocation package', 'Professional development', 'Networking events', 'Mentorship'],
  '2 rounds of interviews + case study',
  ARRAY['finance', 'chicago', 'analysis'],
  NOW(),
  NOW()
),

-- Consulting Internships
(
  'Management Consulting Intern',
  'McKinsey & Company',
  'Work on strategy and organizational development projects. Help clients solve complex business problems through data-driven analysis.',
  ARRAY['Strong analytical skills', 'Problem-solving ability', 'Communication skills'],
  ARRAY['Excel', 'Data Analysis', 'PowerPoint', 'Business Acumen', 'Problem Solving'],
  'Boston, MA',
  '10 weeks',
  6500,
  '2024-06-01'::date,
  '2024-08-15'::date,
  15,
  'full-time',
  'active',
  'admin-user',
  6000,
  7000,
  'Monday-Friday, 40-45 hours/week',
  'Large (10,000+)',
  'Consulting',
  'Strategy',
  ARRAY['Relocation', 'Free lunch', 'Professional coaching', 'Case interview prep'],
  'Resume, case interviews, fit round',
  ARRAY['consulting', 'strategy', 'boston'],
  NOW(),
  NOW()
),
(
  'Business Consulting Intern',
  'Bain & Company',
  'Partner with clients to identify opportunities for growth and operational improvement. Build analytical frameworks and present recommendations.',
  ARRAY['Strong quantitative skills', 'Problem-solving mindset', 'Teamwork ability'],
  ARRAY['Excel', 'PowerPoint', 'Data Analysis', 'Business Strategy', 'Analytics'],
  'San Francisco, CA',
  '10 weeks',
  6500,
  '2024-07-01'::date,
  '2024-09-15'::date,
  12,
  'full-time',
  'active',
  'admin-user',
  6000,
  7000,
  'Monday-Friday, 40-45 hours/week',
  'Large (10,000+)',
  'Consulting',
  'Business Strategy',
  ARRAY['Bay Area housing', 'Free meals', 'Mentorship', 'Networking'],
  'Case interviews, team exercises, final round',
  ARRAY['consulting', 'SF', 'strategy'],
  NOW(),
  NOW()
),

-- Marketing & Business Development
(
  'Marketing Intern',
  'Coca-Cola',
  'Execute marketing campaigns, conduct market research, and support brand strategy. Work on initiatives reaching millions of consumers worldwide.',
  ARRAY['Marketing or Business degree', 'Creative thinking', 'Communication skills'],
  ARRAY['Marketing Analytics', 'Social Media', 'Content Creation', 'Data Analysis', 'Communication'],
  'Atlanta, GA',
  '12 weeks',
  4500,
  '2024-05-15'::date,
  '2024-08-15'::date,
  10,
  'full-time',
  'active',
  'admin-user',
  4000,
  5000,
  'Monday-Friday, 40 hours/week',
  'Large (10,000+)',
  'CPG/Beverage',
  'Marketing',
  ARRAY['Free beverages', 'Networking events', 'Product launch participation', 'Mentorship'],
  '1-2 phone interviews + final round',
  ARRAY['marketing', 'atlanta', 'brand'],
  NOW(),
  NOW()
),
(
  'Business Development Intern',
  'Airbnb',
  'Expand market opportunities by identifying partnerships, analyzing market trends, and supporting growth strategies across regions.',
  ARRAY['Business or Economics background', 'Analytical mindset', 'Communication skills'],
  ARRAY['Market Analysis', 'Data Analysis', 'Strategy', 'Communication', 'Excel'],
  'San Francisco, CA',
  '12 weeks',
  5500,
  '2024-06-01'::date,
  '2024-08-31'::date,
  8,
  'full-time',
  'active',
  'admin-user',
  5000,
  6000,
  'Monday-Friday, 40 hours/week',
  'Large (1,000-10,000)',
  'Travel/Hospitality',
  'Business Development',
  ARRAY['Free travel credits', 'Relocation', 'Free meals', 'Networking'],
  'Case study, interviews, team challenge',
  ARRAY['BD', 'SF', 'travel-tech'],
  NOW(),
  NOW()
),

-- Engineering - Non-Software
(
  'Mechanical Engineering Intern',
  'Tesla',
  'Design and analyze components for electric vehicles. Work on manufacturing processes, CAD modeling, and testing prototypes.',
  ARRAY['Mechanical Engineering major', 'CATIA or SolidWorks experience', 'Physics background'],
  ARRAY['CATIA', 'SolidWorks', 'MATLAB', 'Physics', 'Engineering Design'],
  'Palo Alto, CA',
  '12 weeks',
  6000,
  '2024-06-01'::date,
  '2024-08-31'::date,
  10,
  'full-time',
  'active',
  'admin-user',
  5500,
  6500,
  'Monday-Friday, 40 hours/week',
  'Large (10,000+)',
  'Automotive/Energy',
  'Mechanical Engineering',
  ARRAY['Relocation', 'Free lunch', 'Lab access', 'Patent opportunity'],
  'Technical interviews, design challenge, team fit',
  ARRAY['ME', 'automotive', 'palo-alto'],
  NOW(),
  NOW()
),
(
  'Civil Engineering Intern',
  'Bechtel Corporation',
  'Contribute to large-scale infrastructure projects including highways, bridges, and buildings. Learn project management and site coordination.',
  ARRAY['Civil Engineering major', 'CAD proficiency', 'Site experience preferred'],
  ARRAY['AutoCAD', 'Revit', 'Project Management', 'Site Surveying', 'Construction'],
  'San Francisco, CA',
  '12 weeks',
  5500,
  '2024-06-15'::date,
  '2024-09-15'::date,
  8,
  'full-time',
  'active',
  'admin-user',
  5000,
  6000,
  'Monday-Friday, 40-50 hours/week',
  'Large (10,000+)',
  'Construction/Infrastructure',
  'Civil Engineering',
  ARRAY['Site visits', 'Field experience', 'Mentorship', 'PPE provided'],
  'Technical assessment, interviews, site visit',
  ARRAY['civil', 'infrastructure', 'SF'],
  NOW(),
  NOW()
),

-- Product Management
(
  'Product Management Intern',
  'Uber',
  'Work on product strategy, conduct user research, and support feature launches. Impact millions of users globally.',
  ARRAY['Strong analytical skills', 'User empathy', 'Communication ability'],
  ARRAY['Product Strategy', 'User Research', 'Data Analysis', 'Communication', 'SQL'],
  'San Francisco, CA',
  '12 weeks',
  6000,
  '2024-06-01'::date,
  '2024-08-31'::date,
  6,
  'full-time',
  'active',
  'admin-user',
  5500,
  6500,
  'Monday-Friday, 40 hours/week',
  'Large (10,000+)',
  'Technology',
  'Product Management',
  ARRAY['Free Uber credits', 'Relocation', 'Mentorship from PMs', 'Product impact'],
  'Product exercise, behavioral interviews, exec round',
  ARRAY['PM', 'SF', 'tech'],
  NOW(),
  NOW()
),
(
  'Product Operations Intern',
  'Slack',
  'Support product launches, analyze user metrics, and optimize product workflows. Work cross-functionally with design and engineering.',
  ARRAY['Technical background preferred', 'Analytical skills', 'Project management'],
  ARRAY['Product Analytics', 'SQL', 'Data Visualization', 'Google Analytics', 'Communication'],
  'San Francisco, CA',
  '12 weeks',
  5500,
  '2024-07-01'::date,
  '2024-09-30'::date,
  5,
  'full-time',
  'active',
  'admin-user',
  5000,
  6000,
  'Monday-Friday, 40 hours/week',
  'Large (1,000-10,000)',
  'Technology',
  'Product Operations',
  ARRAY['Free Slack access', 'Mentorship', 'Conference budget', 'Networking'],
  'Analytics challenge, interviews, team fit',
  ARRAY['prodops', 'SF', 'analytics'],
  NOW(),
  NOW()
),

-- Design & UX
(
  'UX/UI Design Intern',
  'Adobe',
  'Design user interfaces and experiences for creative software products. Work with product and engineering teams on user-centric design.',
  ARRAY['Design portfolio', 'Figma or Adobe XD experience', 'UI/UX fundamentals'],
  ARRAY['Figma', 'Adobe XD', 'Prototyping', 'User Research', 'Design Systems'],
  'San Francisco, CA',
  '12 weeks',
  5500,
  '2024-06-01'::date,
  '2024-08-31'::date,
  8,
  'full-time',
  'active',
  'admin-user',
  5000,
  6000,
  'Monday-Friday, 40 hours/week',
  'Large (10,000+)',
  'Technology',
  'Design',
  ARRAY['Creative tools access', 'Design feedback', 'Portfolio review', 'Networking'],
  'Portfolio review, design challenge, interviews',
  ARRAY['UX', 'design', 'SF'],
  NOW(),
  NOW()
),
(
  'Graphic Design Intern',
  'IDEO',
  'Create visual concepts and designs for client projects. Collaborate with strategists and designers on innovative design solutions.',
  ARRAY['Graphic Design background', 'Adobe Creative Suite proficiency', 'Portfolio required'],
  ARRAY['Adobe Creative Suite', 'Brand Design', 'Motion Graphics', 'Illustration', 'Design Thinking'],
  'San Francisco, CA',
  '10 weeks',
  4500,
  '2024-06-15'::date,
  '2024-08-31'::date,
  6,
  'full-time',
  'active',
  'admin-user',
  4000,
  5000,
  'Monday-Friday, 40 hours/week',
  'Medium (1,000-10,000)',
  'Design/Creative',
  'Graphic Design',
  ARRAY['Portfolio feedback', 'Creative mentorship', 'Project ownership', 'Networking'],
  'Portfolio review, design challenge, final round',
  ARRAY['design', 'creative', 'SF'],
  NOW(),
  NOW()
),

-- Sales & Account Management
(
  'Sales Development Rep Intern',
  'Salesforce',
  'Develop business through outreach, demos, and pipeline building. Learn enterprise sales fundamentals with industry-leading CRM.',
  ARRAY['Communication skills', 'Competitive drive', 'Organizational ability'],
  ARRAY['Sales', 'Communication', 'CRM Systems', 'Excel', 'Business Development'],
  'San Francisco, CA',
  '12 weeks',
  5000,
  '2024-06-01'::date,
  '2024-08-31'::date,
  10,
  'full-time',
  'active',
  'admin-user',
  4500,
  5500,
  'Monday-Friday, 40 hours/week',
  'Large (10,000+)',
  'Software/SaaS',
  'Sales',
  ARRAY['Commission opportunity', 'Sales training', 'Mentorship', 'Team events'],
  '1-2 phone interviews + role play round',
  ARRAY['sales', 'SF', 'commission'],
  NOW(),
  NOW()
),
(
  'Account Management Intern',
  'HubSpot',
  'Manage client accounts, ensure customer success, and identify expansion opportunities. Work with enterprise and mid-market clients.',
  ARRAY['Customer service background', 'Communication skills', 'Problem-solving'],
  ARRAY['Account Management', 'CRM', 'Customer Success', 'Communication', 'Sales'],
  'Cambridge, MA',
  '12 weeks',
  5000,
  '2024-06-01'::date,
  '2024-08-31'::date,
  12,
  'full-time',
  'active',
  'admin-user',
  4500,
  5500,
  'Monday-Friday, 40 hours/week',
  'Large (1,000-10,000)',
  'Software/SaaS',
  'Account Management',
  ARRAY['Customer interactions', 'Sales training', 'Mentorship', 'Networking'],
  'Phone interview, case study, final round',
  ARRAY['account-mgmt', 'boston', 'SaaS'],
  NOW(),
  NOW()
),

-- Operations & Supply Chain
(
  'Supply Chain Intern',
  'Amazon',
  'Optimize logistics networks, manage supplier relationships, and improve operations efficiency. Work with world-class supply chain operations.',
  ARRAY['Operations or Engineering background', 'Analytical skills', 'Problem-solving'],
  ARRAY['Supply Chain', 'Excel', 'Analytics', 'SQL', 'Logistics'],
  'Seattle, WA',
  '12 weeks',
  5500,
  '2024-06-01'::date,
  '2024-08-31'::date,
  15,
  'full-time',
  'active',
  'admin-user',
  5000,
  6000,
  'Monday-Friday, 40 hours/week',
  'Large (10,000+)',
  'Retail/E-commerce',
  'Operations',
  ARRAY['Relocation', 'Free Amazon Prime', 'Mentorship', 'Warehouse tours'],
  'Phone screen, interviews, case study',
  ARRAY['operations', 'seattle', 'supply-chain'],
  NOW(),
  NOW()
),
(
  'Operations Analyst Intern',
  'Delta Air Lines',
  'Support flight operations, analyze efficiency metrics, and optimize airline procedures. Work in the fast-paced aviation industry.',
  ARRAY['Operations or Engineering degree', 'Data analysis skills', 'Problem-solving'],
  ARRAY['Operations', 'Data Analysis', 'Excel', 'Logistics', 'Process Improvement'],
  'Atlanta, GA',
  '12 weeks',
  5000,
  '2024-06-01'::date,
  '2024-08-31'::date,
  8,
  'full-time',
  'active',
  'admin-user',
  4500,
  5500,
  'Monday-Friday, 40 hours/week',
  'Large (10,000+)',
  'Aviation',
  'Operations',
  ARRAY['Flight benefits', 'Atlanta base', 'Mentorship', 'Industry insight'],
  'Phone interview, case analysis, final round',
  ARRAY['operations', 'atlanta', 'aviation'],
  NOW(),
  NOW()
);

-- Verify data insertion
SELECT COUNT(*) as total_internships FROM internships WHERE company IN (
  'Goldman Sachs', 'Jane Street', 'JPMorgan Chase', 'McKinsey & Company', 'Bain & Company',
  'Coca-Cola', 'Airbnb', 'Tesla', 'Bechtel Corporation', 'Uber', 'Slack', 'Adobe', 'IDEO',
  'Salesforce', 'HubSpot', 'Amazon', 'Delta Air Lines'
);
