-- Add comprehensive internship data using only the columns that exist in the schema

INSERT INTO internships (
  title, company, description, requirements, skills, location, duration, 
  stipend, positions_available, internship_type, 
  status, created_by, salary_min, salary_max, 
  industry, job_category, perks, selection_process, tags,
  created_at, updated_at
) VALUES
-- Finance & Banking
(
  'Investment Banking Analyst Intern',
  'Goldman Sachs',
  'Work on financial modeling, valuation analysis, and M&A transactions. Gain exposure to capital markets and work with senior bankers on deals.',
  ARRAY['Finance background', 'Excel expertise', 'Financial modeling'],
  ARRAY['Excel', 'Financial Modeling', 'Valuation', 'SQL', 'Python'],
  'New York, NY',
  '10 weeks',
  '8000',
  8,
  'full-time',
  'active',
  NULL,
  7500,
  9000,
  'Finance',
  'Investment Banking',
  ARRAY['Competitive stipend', 'Return offer potential', 'Networking dinners'],
  'Online test, 3 rounds interviews',
  ARRAY['banking', 'NYC', 'high-pay'],
  NOW(),
  NOW()
),
(
  'Quantitative Analysis Intern',
  'Jane Street',
  'Build and test trading strategies using statistical analysis and machine learning for algorithmic trading.',
  ARRAY['Math background', 'Programming', 'Probability and statistics'],
  ARRAY['Python', 'C++', 'Statistics', 'Machine Learning', 'Data Analysis'],
  'New York, NY',
  '12 weeks',
  '7500',
  12,
  'full-time',
  'active',
  NULL,
  7000,
  8500,
  'Finance',
  'Quantitative Analysis',
  ARRAY['Free lunch', 'Gym membership', 'Tech gadgets', 'Mentorship'],
  'Phone screening, coding challenges',
  ARRAY['quant', 'trading', 'NYC'],
  NOW(),
  NOW()
),
(
  'Financial Analyst Intern',
  'JPMorgan Chase',
  'Analyze financial statements, build forecasting models, and support portfolio management across business lines.',
  ARRAY['Finance major', 'Analytical skills', 'Financial concepts knowledge'],
  ARRAY['Excel', 'Financial Analysis', 'SQL', 'Python'],
  'Chicago, IL',
  '10 weeks',
  '6000',
  20,
  'full-time',
  'active',
  NULL,
  5500,
  6500,
  'Finance',
  'Financial Analysis',
  ARRAY['Relocation package', 'Professional development', 'Mentorship'],
  '2 rounds interviews + case study',
  ARRAY['finance', 'chicago'],
  NOW(),
  NOW()
),

-- Consulting
(
  'Management Consulting Intern',
  'McKinsey & Company',
  'Work on strategy projects. Help clients solve complex business problems through data-driven analysis.',
  ARRAY['Analytical skills', 'Problem-solving', 'Communication'],
  ARRAY['Excel', 'Data Analysis', 'PowerPoint', 'Problem Solving'],
  'Boston, MA',
  '10 weeks',
  '6500',
  15,
  'full-time',
  'active',
  NULL,
  6000,
  7000,
  'Consulting',
  'Strategy',
  ARRAY['Relocation', 'Free meals', 'Professional coaching'],
  'Resume, case interviews, fit round',
  ARRAY['consulting', 'boston'],
  NOW(),
  NOW()
),
(
  'Business Consulting Intern',
  'Bain & Company',
  'Identify growth opportunities and operational improvements. Build frameworks and present recommendations to clients.',
  ARRAY['Quantitative skills', 'Problem-solving', 'Teamwork'],
  ARRAY['Excel', 'PowerPoint', 'Data Analysis', 'Business Strategy'],
  'San Francisco, CA',
  '10 weeks',
  '6500',
  12,
  'full-time',
  'active',
  NULL,
  6000,
  7000,
  'Consulting',
  'Business Strategy',
  ARRAY['Bay Area housing', 'Free meals', 'Mentorship', 'Networking'],
  'Case interviews, team exercises',
  ARRAY['consulting', 'SF'],
  NOW(),
  NOW()
),

-- Marketing & Business Development
(
  'Marketing Intern',
  'Coca-Cola',
  'Execute marketing campaigns, conduct market research, and support brand strategy for global consumer brands.',
  ARRAY['Marketing degree', 'Creative thinking', 'Communication'],
  ARRAY['Marketing Analytics', 'Social Media', 'Content Creation', 'Data Analysis'],
  'Atlanta, GA',
  '12 weeks',
  '4500',
  10,
  'full-time',
  'active',
  NULL,
  4000,
  5000,
  'CPG/Beverage',
  'Marketing',
  ARRAY['Free beverages', 'Networking events', 'Product launch', 'Mentorship'],
  '1-2 phone interviews + final',
  ARRAY['marketing', 'atlanta'],
  NOW(),
  NOW()
),
(
  'Business Development Intern',
  'Airbnb',
  'Expand market opportunities by identifying partnerships and analyzing market trends across regions.',
  ARRAY['Business background', 'Analytical mindset', 'Communication'],
  ARRAY['Market Analysis', 'Data Analysis', 'Strategy', 'Excel'],
  'San Francisco, CA',
  '12 weeks',
  '5500',
  8,
  'full-time',
  'active',
  NULL,
  5000,
  6000,
  'Travel/Hospitality',
  'Business Development',
  ARRAY['Free travel credits', 'Relocation', 'Free meals', 'Networking'],
  'Case study, interviews, team challenge',
  ARRAY['BD', 'SF', 'travel'],
  NOW(),
  NOW()
),

-- Engineering
(
  'Mechanical Engineering Intern',
  'Tesla',
  'Design and analyze components for electric vehicles. Work on manufacturing processes, CAD modeling, and prototypes.',
  ARRAY['Mechanical Engineering major', 'CATIA or SolidWorks', 'Physics'],
  ARRAY['CATIA', 'SolidWorks', 'MATLAB', 'Physics', 'Engineering Design'],
  'Palo Alto, CA',
  '12 weeks',
  '6000',
  10,
  'full-time',
  'active',
  NULL,
  5500,
  6500,
  'Automotive/Energy',
  'Mechanical Engineering',
  ARRAY['Relocation', 'Free lunch', 'Lab access', 'Patent opportunity'],
  'Technical interviews, design challenge',
  ARRAY['ME', 'automotive'],
  NOW(),
  NOW()
),
(
  'Civil Engineering Intern',
  'Bechtel Corporation',
  'Contribute to large-scale infrastructure projects including highways, bridges, and buildings.',
  ARRAY['Civil Engineering major', 'CAD proficiency', 'Site experience'],
  ARRAY['AutoCAD', 'Revit', 'Project Management', 'Site Surveying'],
  'San Francisco, CA',
  '12 weeks',
  '5500',
  8,
  'full-time',
  'active',
  NULL,
  5000,
  6000,
  'Construction/Infrastructure',
  'Civil Engineering',
  ARRAY['Site visits', 'Field experience', 'Mentorship'],
  'Technical assessment, interviews',
  ARRAY['civil', 'infrastructure'],
  NOW(),
  NOW()
),

-- Product & Tech
(
  'Product Management Intern',
  'Uber',
  'Work on product strategy, conduct user research, and support feature launches impacting millions of users.',
  ARRAY['Analytical skills', 'User empathy', 'Communication'],
  ARRAY['Product Strategy', 'User Research', 'Data Analysis', 'SQL'],
  'San Francisco, CA',
  '12 weeks',
  '6000',
  6,
  'full-time',
  'active',
  NULL,
  5500,
  6500,
  'Technology',
  'Product Management',
  ARRAY['Free Uber credits', 'Relocation', 'PM Mentorship', 'Product impact'],
  'Product exercise, behavioral interviews',
  ARRAY['PM', 'SF'],
  NOW(),
  NOW()
),
(
  'Product Operations Intern',
  'Slack',
  'Support product launches, analyze metrics, and optimize workflows. Work cross-functionally with design and engineering.',
  ARRAY['Technical background', 'Analytical skills', 'Project management'],
  ARRAY['Product Analytics', 'SQL', 'Data Visualization', 'Google Analytics'],
  'San Francisco, CA',
  '12 weeks',
  '5500',
  5,
  'full-time',
  'active',
  NULL,
  5000,
  6000,
  'Technology',
  'Product Operations',
  ARRAY['Free Slack access', 'Mentorship', 'Conference budget'],
  'Analytics challenge, interviews',
  ARRAY['prodops', 'SF'],
  NOW(),
  NOW()
),

-- Design
(
  'UX/UI Design Intern',
  'Adobe',
  'Design user interfaces for creative software products. Work with product and engineering on user-centric design.',
  ARRAY['Design portfolio', 'Figma or Adobe XD', 'UI/UX fundamentals'],
  ARRAY['Figma', 'Adobe XD', 'Prototyping', 'User Research', 'Design Systems'],
  'San Francisco, CA',
  '12 weeks',
  '5500',
  8,
  'full-time',
  'active',
  NULL,
  5000,
  6000,
  'Technology',
  'Design',
  ARRAY['Creative tools', 'Design feedback', 'Portfolio review'],
  'Portfolio review, design challenge',
  ARRAY['UX', 'design'],
  NOW(),
  NOW()
),
(
  'Graphic Design Intern',
  'IDEO',
  'Create visual concepts and designs for client projects. Collaborate with strategists on innovative design solutions.',
  ARRAY['Graphic Design background', 'Adobe Creative Suite', 'Portfolio'],
  ARRAY['Adobe Creative Suite', 'Brand Design', 'Motion Graphics', 'Illustration'],
  'San Francisco, CA',
  '10 weeks',
  '4500',
  6,
  'full-time',
  'active',
  NULL,
  4000,
  5000,
  'Design/Creative',
  'Graphic Design',
  ARRAY['Portfolio feedback', 'Creative mentorship', 'Project ownership'],
  'Portfolio review, design challenge',
  ARRAY['design', 'creative'],
  NOW(),
  NOW()
),

-- Sales
(
  'Sales Development Rep Intern',
  'Salesforce',
  'Develop business through outreach, demos, and pipeline building. Learn enterprise sales fundamentals.',
  ARRAY['Communication skills', 'Competitive drive', 'Organization'],
  ARRAY['Sales', 'Communication', 'CRM Systems', 'Excel'],
  'San Francisco, CA',
  '12 weeks',
  '5000',
  10,
  'full-time',
  'active',
  NULL,
  4500,
  5500,
  'Software/SaaS',
  'Sales',
  ARRAY['Commission opportunity', 'Sales training', 'Mentorship'],
  '1-2 phone interviews + role play',
  ARRAY['sales', 'SF'],
  NOW(),
  NOW()
),
(
  'Account Management Intern',
  'HubSpot',
  'Manage client accounts, ensure customer success, and identify expansion opportunities with enterprise clients.',
  ARRAY['Customer service', 'Communication', 'Problem-solving'],
  ARRAY['Account Management', 'CRM', 'Customer Success', 'Sales'],
  'Cambridge, MA',
  '12 weeks',
  '5000',
  12,
  'full-time',
  'active',
  NULL,
  4500,
  5500,
  'Software/SaaS',
  'Account Management',
  ARRAY['Customer interactions', 'Sales training', 'Mentorship'],
  'Phone interview, case study',
  ARRAY['account-mgmt', 'boston'],
  NOW(),
  NOW()
),

-- Operations
(
  'Supply Chain Intern',
  'Amazon',
  'Optimize logistics networks, manage suppliers, and improve operations efficiency at world-class scale.',
  ARRAY['Operations background', 'Analytical skills', 'Problem-solving'],
  ARRAY['Supply Chain', 'Excel', 'Analytics', 'SQL', 'Logistics'],
  'Seattle, WA',
  '12 weeks',
  '5500',
  15,
  'full-time',
  'active',
  NULL,
  5000,
  6000,
  'Retail/E-commerce',
  'Operations',
  ARRAY['Relocation', 'Free Prime', 'Mentorship', 'Warehouse tours'],
  'Phone screen, interviews, case study',
  ARRAY['operations', 'seattle'],
  NOW(),
  NOW()
),
(
  'Operations Analyst Intern',
  'Delta Air Lines',
  'Support flight operations, analyze efficiency metrics, and optimize airline procedures in aviation industry.',
  ARRAY['Operations degree', 'Data analysis', 'Problem-solving'],
  ARRAY['Operations', 'Data Analysis', 'Excel', 'Logistics'],
  'Atlanta, GA',
  '12 weeks',
  '5000',
  8,
  'full-time',
  'active',
  NULL,
  4500,
  5500,
  'Aviation',
  'Operations',
  ARRAY['Flight benefits', 'Atlanta base', 'Mentorship'],
  'Phone interview, case analysis',
  ARRAY['operations', 'atlanta'],
  NOW(),
  NOW()
);

-- Verify insertion
SELECT COUNT(*) as total_internships FROM internships;
