-- Seed sample internship data with detailed information

INSERT INTO internships (
  title, company, description, requirements, skills, location, duration, 
  stipend, start_date, end_date, positions_available, internship_type, 
  status, created_by, salary_min, salary_max, work_schedule, company_size,
  industry, job_category, perks, min_gpa, required_certifications,
  about_company, learning_outcomes, host_name, host_email,
  created_at, updated_at
) VALUES
-- Tech Company Internships
(
  'Software Engineering Intern',
  'Google',
  'Join Google''s engineering team to work on cutting-edge technologies. You''ll contribute to real-world projects, collaborate with experienced engineers, and gain hands-on experience with cloud computing and distributed systems.',
  ARRAY['Bachelor''s in Computer Science or related field', 'Strong programming fundamentals', 'Experience with one or more programming languages'],
  ARRAY['Python', 'Java', 'JavaScript', 'Cloud Computing', 'Algorithms', 'Data Structures'],
  'Mountain View, CA',
  '12 weeks',
  5000,
  '2024-06-01'::date,
  '2024-08-31'::date,
  15,
  'full-time',
  'active',
  'admin-user',
  5500,
  7000,
  'Monday-Friday, 40 hours/week',
  'Large (10,000+)',
  'Technology',
  'Software Development',
  ARRAY['Free meals and snacks', 'Gym membership', 'Housing stipend', 'Team outings'],
  3.5,
  ARRAY[''],
  'Google is a global technology leader focused on improving how people connect, explore, and interact with information and one another.',
  ARRAY['Learn modern software development practices', 'Experience with large-scale systems', 'Mentorship from senior engineers'],
  'John Smith',
  'hr@google.com',
  NOW(),
  NOW()
),
(
  'Data Science Intern',
  'Microsoft',
  'Work with data science teams to analyze large datasets, build predictive models, and create data visualizations. You''ll learn about machine learning, statistical analysis, and business intelligence while working on real problems that impact millions of users.',
  ARRAY['Experience with Python or R', 'Knowledge of statistics and machine learning', 'SQL proficiency'],
  ARRAY['Python', 'Machine Learning', 'SQL', 'Tableau', 'Statistics', 'Data Analysis'],
  'Seattle, WA',
  '12 weeks',
  5000,
  '2024-06-15'::date,
  '2024-09-15'::date,
  10,
  'full-time',
  'active',
  'admin-user',
  5000,
  6500,
  'Monday-Friday, 40 hours/week',
  'Large (10,000+)',
  'Technology',
  'Data Science',
  ARRAY['Learning resources', 'Conference attendance', 'Networking events', 'Free Microsoft software'],
  3.3,
  ARRAY[''],
  'Microsoft is committed to empowering every person and organization on the planet to achieve more.',
  ARRAY['Master machine learning techniques', 'Work with big data technologies', 'Present findings to stakeholders'],
  'Sarah Johnson',
  'internships@microsoft.com',
  NOW(),
  NOW()
),
(
  'Frontend Developer Intern',
  'Meta',
  'Help build user interfaces that impact billions of users worldwide. Work with React, JavaScript, and modern web technologies. You''ll collaborate with designers and backend engineers to create seamless user experiences.',
  ARRAY['Knowledge of HTML, CSS, JavaScript', 'Experience with React or similar frameworks', 'Version control with Git'],
  ARRAY['JavaScript', 'React', 'CSS', 'HTML', 'Web Development', 'UI/UX'],
  'Menlo Park, CA',
  '12 weeks',
  5500,
  '2024-07-01'::date,
  '2024-09-30'::date,
  12,
  'full-time',
  'active',
  'admin-user',
  5500,
  7000,
  'Monday-Friday, 40 hours/week',
  'Large (10,000+)',
  'Technology',
  'Web Development',
  ARRAY['Relocation assistance', 'Tech gadgets', 'Professional development', 'Social events'],
  3.4,
  ARRAY[''],
  'Meta builds technologies that help people connect, find communities and grow businesses.',
  ARRAY['Master React and modern JavaScript', 'Learn performance optimization', 'Understand web accessibility'],
  'Mike Chen',
  'careers@meta.com',
  NOW(),
  NOW()
),
-- Finance Internships
(
  'Financial Analysis Intern',
  'Goldman Sachs',
  'Gain experience in financial analysis, investment banking, and market research. You''ll work on analyzing financial statements, building valuation models, and supporting senior analysts on deals and research projects.',
  ARRAY['Strong Excel skills', 'Understanding of financial statements', 'Attention to detail'],
  ARRAY['Excel', 'Financial Modeling', 'Financial Analysis', 'Valuation', 'Python', 'SQL'],
  'New York, NY',
  '10 weeks',
  6000,
  '2024-06-01'::date,
  '2024-08-15'::date,
  8,
  'full-time',
  'active',
  'admin-user',
  6000,
  7500,
  'Monday-Friday, 50 hours/week',
  'Large (10,000+)',
  'Finance',
  'Finance/Banking',
  ARRAY['Mentorship program', 'Networking dinners', 'Financial literacy workshops', 'Housing provided'],
  3.6,
  ARRAY[''],
  'Goldman Sachs is a leading global investment banking and securities firm.',
  ARRAY['Master financial modeling', 'Understand investment processes', 'Develop analytical skills'],
  'Emily Davis',
  'internship@gs.com',
  NOW(),
  NOW()
),
(
  'Risk Management Intern',
  'JPMorgan Chase',
  'Join the Risk Management team to understand how financial institutions manage risk. You''ll work on risk assessments, compliance monitoring, and regulatory reporting for complex financial portfolios.',
  ARRAY['Strong analytical skills', 'Understanding of risk management principles', 'Basic knowledge of financial markets'],
  ARRAY['Risk Analysis', 'Financial Modeling', 'Python', 'SQL', 'Compliance', 'Analytics'],
  'New York, NY',
  '10 weeks',
  5800,
  '2024-06-15'::date,
  '2024-08-31'::date,
  6,
  'full-time',
  'active',
  'admin-user',
  5800,
  7200,
  'Monday-Friday, 45 hours/week',
  'Large (10,000+)',
  'Finance',
  'Risk Management',
  ARRAY['Professional certification support', 'Training programs', 'Team building activities', 'Commuter benefits'],
  3.5,
  ARRAY[''],
  'JPMorgan Chase is a leading global financial services firm.',
  ARRAY['Understand financial risk', 'Learn compliance requirements', 'Master risk analytics tools'],
  'Robert Wilson',
  'talent@jpmorgan.com',
  NOW(),
  NOW()
),
-- Consulting Internships
(
  'Business Strategy Intern',
  'McKinsey & Company',
  'Work alongside experienced consultants on strategic projects for Fortune 500 companies. You''ll conduct market research, develop business recommendations, and present findings to senior executives.',
  ARRAY['Strong communication skills', 'Analytical mindset', 'Interest in business strategy'],
  ARRAY['Business Analysis', 'Market Research', 'Strategic Planning', 'Data Analysis', 'Excel', 'PowerPoint'],
  'Chicago, IL',
  '10 weeks',
  5500,
  '2024-06-01'::date,
  '2024-08-15'::date,
  5,
  'full-time',
  'active',
  'admin-user',
  5500,
  6500,
  'Monday-Friday, 45 hours/week',
  'Large (10,000+)',
  'Consulting',
  'Consulting',
  ARRAY['International travel opportunities', 'Networking with executives', 'Professional development', 'Exclusive events'],
  3.7,
  ARRAY[''],
  'McKinsey & Company is a global management consulting firm.',
  ARRAY['Develop strategic thinking skills', 'Master business problem-solving', 'Build presentation expertise'],
  'Lisa Anderson',
  'recruitment@mckinsey.com',
  NOW(),
  NOW()
),
-- Marketing/Business Internships
(
  'Marketing Intern',
  'Coca-Cola',
  'Support marketing campaigns and brand development strategies. You''ll conduct market research, analyze consumer insights, develop marketing materials, and support product launches.',
  ARRAY['Creativity and marketing knowledge', 'Strong communication skills', 'Social media proficiency'],
  ARRAY['Social Media Marketing', 'Content Creation', 'Market Research', 'Brand Management', 'Analytics', 'Adobe Creative Suite'],
  'Atlanta, GA',
  '12 weeks',
  3000,
  '2024-06-01'::date,
  '2024-08-31'::date,
  10,
  'full-time',
  'active',
  'admin-user',
  3000,
  4500,
  'Monday-Friday, 40 hours/week',
  'Large (10,000+)',
  'Consumer Goods',
  'Marketing',
  ARRAY['Product samples', 'Networking events', 'Professional development', 'Flexible schedule options'],
  3.2,
  ARRAY[''],
  'Coca-Cola is the world''s largest beverage company.',
  ARRAY['Master marketing strategies', 'Learn consumer behavior analysis', 'Develop campaign skills'],
  'Jennifer Martinez',
  'careers@coca-cola.com',
  NOW(),
  NOW()
),
-- Additional startups and companies
(
  'Full Stack Engineer Intern',
  'Uber',
  'Work on Uber''s core platform used by millions globally. You''ll build features, optimize performance, and work with cutting-edge distributed systems.',
  ARRAY['Full-stack development experience', 'Knowledge of backend and frontend technologies', 'Problem-solving skills'],
  ARRAY['JavaScript', 'React', 'Node.js', 'PostgreSQL', 'Docker', 'AWS'],
  'San Francisco, CA',
  '12 weeks',
  5500,
  '2024-06-15'::date,
  '2024-09-15'::date,
  8,
  'full-time',
  'active',
  'admin-user',
  5500,
  7000,
  'Monday-Friday, 40 hours/week',
  'Large (10,000+)',
  'Technology',
  'Software Development',
  ARRAY['Remote flexibility', 'Free transportation', 'Learning stipend', 'Team outings'],
  3.3,
  ARRAY[''],
  'Uber is changing the way people and things move around cities globally.',
  ARRAY['Master scalable systems', 'Learn microservices architecture', 'Understand real-time systems'],
  'Alex Thompson',
  'internships@uber.com',
  NOW(),
  NOW()
),
(
  'Product Manager Intern',
  'Airbnb',
  'Help shape the future of travel and hospitality. Work on product strategy, user research, and feature development for Airbnb''s global platform.',
  ARRAY['Interest in product management', 'Analytical skills', 'Understanding of user experience'],
  ARRAY['Product Management', 'Data Analysis', 'User Research', 'Analytics', 'SQL', 'A/B Testing'],
  'San Francisco, CA',
  '12 weeks',
  4500,
  '2024-06-01'::date,
  '2024-08-31'::date,
  4,
  'full-time',
  'active',
  'admin-user',
  4500,
  5500,
  'Monday-Friday, 40 hours/week',
  'Large (10,000+)',
  'Technology',
  'Product Management',
  ARRAY['Travel credits', 'Product training', 'Mentorship', 'Industry events'],
  3.4,
  ARRAY[''],
  'Airbnb is a global hospitality platform connecting travelers with unique accommodations.',
  ARRAY['Learn product strategy', 'Master user research methods', 'Develop analytical skills'],
  'Jessica Lee',
  'careers@airbnb.com',
  NOW(),
  NOW()
);

-- Create an admin user for testing
INSERT INTO users (email, password_hash, name, role, created_at)
VALUES (
  'admin@internship.com',
  '$2b$10$YourHashedPasswordHere',
  'Admin User',
  'recruiter',
  NOW()
) ON CONFLICT (email) DO NOTHING;
